[package]
name = "morsgul"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive", "env"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
epicars = { path = "epicars" }
